spring:
  application:
    name: security-security
  datasource:
    url: jdbc:h2:mem:security-security
    driverClassName: org.h2.Driver
    username: root
    password: root
  jpa:
    hibernate:
      naming:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
token:
  signing:
    key: ${SIGNING_KEY}