name: Security Check
run-name: ${{ github.actor }} is testing out GitHub Actions ðŸš€

on: [push]

jobs:
  Static_analyzer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: OWASP Dependency Check
        run: mvn verify
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
