name: Security Check
run-name: ${{ github.actor }} is testing out GitHub Actions ðŸš€
on: [push]
jobs:
  Static_analyzer:
    runs-on: ubuntu-latest
    steps:
      - name: Check secrets
        run: echo "${{ secrets.NVD_API_KEY }}"
      - name: OWASP Dependency Check
        run: mvn verify -Dnvd.api.key="${{ secrets.NVD_API_KEY }}"
